/* ═══════════════════════════════════════════════════
   scholarships.js
   THE SINGLE SOURCE OF TRUTH.
   To add/edit/delete a scholarship: just edit this array.
   Each object follows the same template.
═══════════════════════════════════════════════════ */

const SCHOLARSHIPS = [

  /* ── TEMPLATE (copy-paste to add new) ──────────────
  {
    id: 'unique-id',
    name: 'Scholarship Name',
    org: 'Offering Organization',
    type: 'Government' | 'Private' | 'Foundation' | 'LGU',
    emoji: '🎓',
    imgBg: 'linear-gradient(135deg,#dbeafe,#e0e7ff)',
    region: 'Region Name',          // matches PSGC region name
    province: 'Province Name',      // or '' for nationwide
    city: 'City Name',              // or ''
    barangay: '',                   // or specific barangay
    amount: '₱30,000/yr',
    slots: '500 slots',
    deadline: '2025-03-31',         // YYYY-MM-DD
    level: 'College' | 'Senior High' | 'Graduate' | 'Elementary',
    requirements: ['Req 1', 'Req 2'],
    description: 'Full paragraph description.',
    applyUrl: '#',
  },
  ── END TEMPLATE ─────────────────────────────────── */

  {
    id: 'ched-tulong-dunong-2025',
    name: 'CHED Tulong Dunong Program',
    org: 'Commission on Higher Education',
    type: 'Government',
    emoji: '🎓',
    imgBg: 'linear-gradient(135deg,#dbeafe,#e0e7ff)',
    region: 'Davao Region',
    province: 'Davao del Sur',
    city: 'Digos City',
    barangay: '',
    amount: '₱30,000/yr',
    slots: '500 slots',
    deadline: '2025-03-31',
    level: 'College',
    requirements: ['Filipino Citizen','GWA 1.75 or higher','Incoming College Student','Annual Income ≤ ₱400,000','No existing scholarship'],
    description: 'The CHED Tulong Dunong Program provides financial assistance to deserving but financially challenged students pursuing tertiary education. The program aims to increase access to quality higher education for underprivileged students nationwide, prioritizing those in remote and underserved areas.',
    applyUrl: '#',
  },
  {
    id: 'sm-foundation-2025',
    name: 'SM Foundation College Scholarship',
    org: 'SM Foundation Inc.',
    type: 'Foundation',
    emoji: '🏫',
    imgBg: 'linear-gradient(135deg,#dcfce7,#d1fae5)',
    region: 'Davao Region',
    province: 'Davao del Sur',
    city: 'Davao City',
    barangay: '',
    amount: '₱60,000/yr',
    slots: '200 slots',
    deadline: '2025-06-15',
    level: 'College',
    requirements: ['High School Graduate','GWA 85% or higher','Annual Income ≤ ₱200,000','Enrolled in partner school','Good moral character'],
    description: 'SM Foundation provides full college scholarships to academically deserving but financially challenged students. Scholars receive monthly stipends, school allowances, and must maintain academic standards throughout the program duration.',
    applyUrl: '#',
  },
  {
    id: 'dost-sei-merit-2025',
    name: 'DOST-SEI Merit Scholarship',
    org: 'Dept. of Science and Technology',
    type: 'Government',
    emoji: '⭐',
    imgBg: 'linear-gradient(135deg,#fef3c7,#fde68a)',
    region: 'Davao Region',
    province: 'Davao del Norte',
    city: 'Tagum City',
    barangay: '',
    amount: '₱40,000/yr',
    slots: '100 slots',
    deadline: '2025-02-28',
    level: 'College',
    requirements: ['Science or Tech course','NSAT Top 10%','Graduating High School','GWA top 10% of class','No failing grades'],
    description: 'The DOST-SEI Merit Scholarship is a highly competitive program for students pursuing science and technology courses. Scholars are provided full tuition, monthly stipend, and book allowance. Scholars are expected to work in the Philippines for at least 2 years post-graduation.',
    applyUrl: '#',
  },
  {
    id: 'ayala-iskolar-2025',
    name: 'Ayala Foundation Iskolar ng Bayan',
    org: 'Ayala Foundation',
    type: 'Foundation',
    emoji: '🌸',
    imgBg: 'linear-gradient(135deg,#fce7f3,#fbcfe8)',
    region: 'Davao Region',
    province: 'Davao Oriental',
    city: 'Mati City',
    barangay: '',
    amount: '₱75,000/yr',
    slots: '50 slots',
    deadline: '2025-08-01',
    level: 'College',
    requirements: ['Leadership track record','GWA 90% or higher','Community service','Essay submission','Interview required'],
    description: 'Ayala Foundation Iskolar ng Bayan supports outstanding students who demonstrate academic excellence and strong community involvement. This holistic scholarship values leadership, service, and character alongside performance.',
    applyUrl: '#',
  },
  {
    id: 'ched-graduate-2025',
    name: 'CHED Graduate Scholarship Program',
    org: 'Commission on Higher Education',
    type: 'Government',
    emoji: '🔬',
    imgBg: 'linear-gradient(135deg,#ede9fe,#ddd6fe)',
    region: '',
    province: '',
    city: '',
    barangay: '',
    amount: '₱120,000/yr',
    slots: '150 slots',
    deadline: '2025-09-30',
    level: 'Graduate',
    requirements: ['Graduate-level enrollment','Research proposal','Letter of endorsement','BS degree from accredited school'],
    description: 'CHED provides graduate-level scholarships to exceptional students pursuing master\'s and doctoral programs in priority fields. This program helps build a pool of highly trained Filipino researchers and educators.',
    applyUrl: '#',
  },
  {
    id: 'jollibee-blt-2025',
    name: 'Jollibee Foundation Busog Lusog Talino',
    org: 'Jollibee Foundation',
    type: 'Foundation',
    emoji: '🌿',
    imgBg: 'linear-gradient(135deg,#ecfdf5,#a7f3d0)',
    region: 'CALABARZON',
    province: 'Laguna',
    city: 'Santa Cruz',
    barangay: '',
    amount: '₱12,000/yr',
    slots: '1000 slots',
    deadline: '2025-07-15',
    level: 'Elementary',
    requirements: ['Elementary student','Family in agriculture sector','Teacher endorsement','Family income ≤ ₱100,000'],
    description: 'Jollibee Foundation\'s BLT program provides nutrition and education support to elementary students from farming families. Students receive daily meals, school supplies, and annual stipends to keep them in school.',
    applyUrl: '#',
  },
  {
    id: 'gsis-scholarship-2025',
    name: 'GSIS Educational Assistance Program',
    org: 'Government Service Insurance System',
    type: 'Government',
    emoji: '🏛️',
    imgBg: 'linear-gradient(135deg,#f0f9ff,#bae6fd)',
    region: 'NCR',
    province: '',
    city: 'Pasay City',
    barangay: '',
    amount: '₱18,000/yr',
    slots: '300 slots',
    deadline: '2025-05-31',
    level: 'College',
    requirements: ['Child of GSIS member','GWA 85%+','Enrolled in state/local university','Financial need','Non-scholar of other govt programs'],
    description: 'GSIS Educational Assistance is exclusively for qualified dependents of GSIS members. It covers tuition fees and provides an annual allowance to help government employees\' children access quality higher education.',
    applyUrl: '#',
  },
  {
    id: 'sss-scholarship-2025',
    name: 'SSS Educational Loan & Scholarship',
    org: 'Social Security System',
    type: 'Government',
    emoji: '📋',
    imgBg: 'linear-gradient(135deg,#fff7ed,#fed7aa)',
    region: 'NCR',
    province: '',
    city: 'Quezon City',
    barangay: '',
    amount: '₱15,000/yr',
    slots: '200 slots',
    deadline: '2025-04-30',
    level: 'College',
    requirements: ['Dependent of SSS member','Member in good standing','GWA 80%+','Annual family income ≤ ₱180,000'],
    description: 'SSS provides educational assistance to qualified dependents of active SSS members. The program aims to support private sector employees\' children in pursuing a college education with reduced financial burden.',
    applyUrl: '#',
  },
  {
    id: 'pcso-medical-scholarship',
    name: 'PCSO Medical Scholarship Program',
    org: 'Philippine Charity Sweepstakes Office',
    type: 'Government',
    emoji: '🏥',
    imgBg: 'linear-gradient(135deg,#fdf2f8,#fce7f3)',
    region: '',
    province: '',
    city: '',
    barangay: '',
    amount: '₱50,000/yr',
    slots: '60 slots',
    deadline: '2025-03-15',
    level: 'College',
    requirements: ['Medical or nursing course','GWA 88%+','Filipino citizen','Financial need certification','Commitment to serve rural areas'],
    description: 'PCSO Medical Scholarship supports students enrolled in medical and nursing courses with a commitment to serve underserved communities after graduation. Priority is given to students from Geographically Isolated and Disadvantaged Areas (GIDAs).',
    applyUrl: '#',
  },
  {
    id: 'dep-ed-senior-high',
    name: 'DepEd Senior High School Voucher',
    org: 'Department of Education',
    type: 'Government',
    emoji: '📚',
    imgBg: 'linear-gradient(135deg,#f0fdf4,#dcfce7)',
    region: '',
    province: '',
    city: '',
    barangay: '',
    amount: '₱22,500/yr',
    slots: 'Open slots',
    deadline: '2025-06-30',
    level: 'Senior High',
    requirements: ['Grade 10 completer','Enrolled in private SHS','ESC certificate','Philippine citizenship'],
    description: 'The DepEd Senior High School Voucher Program allows Grade 10 completers to enroll in non-DepEd schools by covering a portion of their tuition. It expands access to quality senior high school education across the country.',
    applyUrl: '#',
  },
  {
    id: 'tesda-scholarship-2025',
    name: 'TESDA Tech-Voc Scholarship',
    org: 'Technical Education and Skills Development Authority',
    type: 'Government',
    emoji: '🔧',
    imgBg: 'linear-gradient(135deg,#f8fafc,#e2e8f0)',
    region: '',
    province: '',
    city: '',
    barangay: '',
    amount: '₱25,000 (one-time)',
    slots: 'Open',
    deadline: '2025-12-31',
    level: 'College',
    requirements: ['Filipino citizen','TVET program enrollment','Passed TESDA assessment','No other TESDA grant'],
    description: 'TESDA offers training scholarships for technical-vocational programs nationwide. Scholars gain free skills training, tools, and certification fees, preparing them for immediate employment or livelihood opportunities.',
    applyUrl: '#',
  },
  {
    id: 'meralco-scholarship-2025',
    name: 'MERALCO Foundation Scholarship',
    org: 'MERALCO Foundation',
    type: 'Foundation',
    emoji: '💡',
    imgBg: 'linear-gradient(135deg,#fefce8,#fef9c3)',
    region: 'NCR',
    province: '',
    city: 'Pasig City',
    barangay: '',
    amount: '₱45,000/yr',
    slots: '80 slots',
    deadline: '2025-04-15',
    level: 'College',
    requirements: ['Engineering or CS course','GWA 88%+','MERALCO franchise area resident','Annual income ≤ ₱300,000'],
    description: 'MERALCO Foundation awards scholarships to students pursuing engineering and computer science courses. Scholars benefit from mentorship programs, internship opportunities, and possible employment at MERALCO after graduation.',
    applyUrl: '#',
  },
  {
    id: 'globe-bridgcom-2025',
    name: 'Globe Bridgecom Scholarship',
    org: 'Globe Telecom',
    type: 'Private',
    emoji: '📡',
    imgBg: 'linear-gradient(135deg,#eff6ff,#dbeafe)',
    region: '',
    province: '',
    city: '',
    barangay: '',
    amount: '₱55,000/yr',
    slots: '40 slots',
    deadline: '2025-05-30',
    level: 'College',
    requirements: ['STEM strand graduate','GWA 90%+','Aptitude test required','Interview process'],
    description: 'Globe Telecom\'s Bridgecom Scholarship Program supports exceptional STEM students in pursuing technology-related courses. Scholars gain access to industry mentors, hackathons, and a direct career path at Globe.',
    applyUrl: '#',
  },
  {
    id: 'aboitiz-scholarship-2025',
    name: 'Aboitiz Foundation Scholarship',
    org: 'Aboitiz Foundation',
    type: 'Foundation',
    emoji: '⚡',
    imgBg: 'linear-gradient(135deg,#fdf4ff,#fae8ff)',
    region: 'Central Visayas',
    province: 'Cebu',
    city: 'Cebu City',
    barangay: '',
    amount: '₱70,000/yr',
    slots: '60 slots',
    deadline: '2025-07-31',
    level: 'College',
    requirements: ['Resident of Aboitiz host community','GWA 85%+','Financial need','Must take priority courses'],
    description: 'Aboitiz Foundation invests in the education of young people from communities where Aboitiz Group companies operate. Scholars receive tuition grants, living allowances, and leadership development training.',
    applyUrl: '#',
  },
  {
    id: 'pagcor-scholarship-2025',
    name: 'PAGCOR Educational Assistance',
    org: 'Philippine Amusement and Gaming Corporation',
    type: 'Government',
    emoji: '🃏',
    imgBg: 'linear-gradient(135deg,#fff1f2,#ffe4e6)',
    region: '',
    province: '',
    city: '',
    barangay: '',
    amount: '₱20,000/yr',
    slots: '250 slots',
    deadline: '2025-06-01',
    level: 'College',
    requirements: ['Financial need','GWA 80%+','Filipino citizen','Not currently employed'],
    description: 'PAGCOR uses a portion of its revenues to fund educational assistance for deserving Filipino students. The program is open to all courses and is awarded on a need-basis with a focus on financially marginalized applicants.',
    applyUrl: '#',
  },
  {
    id: 'bdo-unibank-scholarship',
    name: 'BDO Foundation Scholarship Program',
    org: 'BDO Foundation',
    type: 'Private',
    emoji: '🏦',
    imgBg: 'linear-gradient(135deg,#f0fdf4,#d1fae5)',
    region: '',
    province: '',
    city: '',
    barangay: '',
    amount: '₱48,000/yr',
    slots: '100 slots',
    deadline: '2025-08-31',
    level: 'College',
    requirements: ['Business or Finance course','GWA 88%+','Financial need','Leadership potential'],
    description: 'BDO Foundation\'s scholarship is geared toward students pursuing Business, Finance, and Accountancy. Scholars may also participate in BDO\'s internship and management trainee programs, opening doors to a career in banking.',
    applyUrl: '#',
  },
  {
    id: 'pnb-scholars-2025',
    name: 'PNB Scholarship for Excellence',
    org: 'Philippine National Bank',
    type: 'Private',
    emoji: '🏧',
    imgBg: 'linear-gradient(135deg,#f0f9ff,#e0f2fe)',
    region: 'NCR',
    province: '',
    city: 'Manila',
    barangay: '',
    amount: '₱36,000/yr',
    slots: '70 slots',
    deadline: '2025-05-15',
    level: 'College',
    requirements: ['Economics, Business, or Law','GWA 87%+','Leadership involvement','Good moral character certificate'],
    description: 'Philippine National Bank awards scholarships to outstanding students in Economics, Business, and Law who demonstrate strong academic performance and leadership. Scholars gain mentorship from PNB executives and possible placement opportunities.',
    applyUrl: '#',
  },
  {
    id: 'lgu-davao-scholars-2025',
    name: 'Davao City LGU Scholarship',
    org: 'City Government of Davao',
    type: 'LGU',
    emoji: '🏙️',
    imgBg: 'linear-gradient(135deg,#fff7ed,#ffedd5)',
    region: 'Davao Region',
    province: 'Davao del Sur',
    city: 'Davao City',
    barangay: '',
    amount: '₱24,000/yr',
    slots: '400 slots',
    deadline: '2025-06-30',
    level: 'College',
    requirements: ['Davao City resident for 3+ years','GWA 85%+','Barangay clearance','No other LGU scholarship'],
    description: 'Davao City provides scholarship grants to qualified residents pursuing college degrees. Priority is given to courses aligned with the city\'s development agenda such as agriculture, engineering, health, and education.',
    applyUrl: '#',
  },
  {
    id: 'manila-city-scholar',
    name: 'City of Manila Scholarship Grant',
    org: 'City Government of Manila',
    type: 'LGU',
    emoji: '🌆',
    imgBg: 'linear-gradient(135deg,#f5f3ff,#ede9fe)',
    region: 'NCR',
    province: '',
    city: 'Manila',
    barangay: '',
    amount: '₱20,000/yr',
    slots: '600 slots',
    deadline: '2025-07-01',
    level: 'College',
    requirements: ['Manila resident','Voter reg. or birth cert.','GWA 82%+','Family income ≤ ₱250,000'],
    description: 'The City of Manila offers annual scholarship grants to deserving residents enrolled in accredited colleges and universities. The program prioritizes students from urban poor communities and those excelling academically despite financial hardship.',
    applyUrl: '#',
  },
  {
    id: 'robinsons-scholars-2025',
    name: 'Robinsons Scholars Program',
    org: 'JG Summit Holdings',
    type: 'Private',
    emoji: '🛍️',
    imgBg: 'linear-gradient(135deg,#fdf2f8,#fce7f3)',
    region: '',
    province: '',
    city: '',
    barangay: '',
    amount: '₱40,000/yr',
    slots: '90 slots',
    deadline: '2025-09-15',
    level: 'College',
    requirements: ['Business, Engineering, or IT','GWA 86%+','Leadership activities','Passed aptitude exam'],
    description: 'JG Summit\'s Robinsons Scholars Program nurtures future business leaders in Business, Engineering, and IT. Scholars receive full tuition support, quarterly stipends, and are given priority consideration for JG Summit group employment.',
    applyUrl: '#',
  },

];

/* ─────────────────────────────────────────────────────────
   Utility helpers — used by app.js, do not modify
───────────────────────────────────────────────────────── */

/**
 * Format deadline date to readable string.
 * Returns { label, urgency: 'urgent'|'soon'|'safe'|'expired' }
 */
function formatDeadline(dateStr) {
    const today    = new Date();
    const deadline = new Date(dateStr);
    const diffMs   = deadline - today;
    const diffDays = Math.ceil(diffMs / (1000 * 60 * 60 * 24));

    const label = deadline.toLocaleDateString('en-PH', { month: 'short', day: 'numeric', year: 'numeric' });

    let urgency = 'safe';
    if (diffDays < 0)  urgency = 'expired';
    else if (diffDays <= 14) urgency = 'urgent';
    else if (diffDays <= 45) urgency = 'soon';

    return { label, urgency, diffDays };
}

/**
 * Get breadcrumb array for a scholarship.
 */
function getLocationBreadcrumb(s) {
    if (!s.region && !s.province && !s.city) return ['Nationwide'];
    return [s.region, s.province, s.city, s.barangay].filter(Boolean);
}